### ISSUE TITLE
 make-pickle.py

### ISSUE THREAD

**Issue by Nikhil-Bajaj** [Tachionstrahl/SignLanguageRecognition#1]
Please help me to know the structure of pickle file
I have combined all the json file features in text file for hands

**Comment by MitchDtown** [comment]
Hi Nikhil,
can you be a little bit more specific about your problem?
We would need some  more information about what is happening or what you are trying to do.

**Comment by Nikhil-Bajaj** [comment]
Sorry got it...I am working on a similar project using  Google OpenPose.
