### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by yspollen** [Tachionstrahl/SignLanguageRecognition#4]
Thank you for the useful repo. 

I'm running MediaPipe on my mac and even though I have Bazel 3.5, I was able to run the Hello World example.

When running ./build_prediction.sh I get the following error:

ERROR: /private/var/tmp/_bazel_[hiddenusername]/8ace2bb3b3c7a44b1439e632e4b7edde/external/local_config_cc/BUILD:48:19: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'darwin_x86_64'

I suspect this is because I don't have Bazel 3.4, but any suggestion is helpful! Thank you.

**Comment by Tachionstrahl** [comment]
Hi @yspollen,
thanks for your request.
Currently we do not support MacOS. 
Please make sure your system matches the listed requirements.
Although we built graphs for CPU, they are not up-to-date at the moment.

**Comment by yspollen** [comment]
Thank you for clarifying!
