### ISSUE TITLE
./run_prediction.sh issue

### ISSUE THREAD

**Issue by yspollen** [Tachionstrahl/SignLanguageRecognition#5]
Hi, thank you for this repo!

When I try to build and run the program, it was able to build successfully, but an issue occurs when I run it. Here's the output error:

I20201021 17:38:34.979502 11882 demo_run_graph_main_gpu.cc:57] Initialize the calculator graph.
I20201021 17:38:34.984632 11882 demo_run_graph_main_gpu.cc:61] Initialize the GPU.
libEGL warning: DRI2: failed to authenticate
I20201021 17:38:35.311697 11882 gl_context_egl.cc:158] Successfully initialized EGL. Major : 1 Minor: 4
I20201021 17:38:35.343811 11885 gl_context.cc:324] GL version: 3.1 (OpenGL ES 3.1 Mesa 20.0.8)
I20201021 17:38:35.343952 11882 demo_run_graph_main_gpu.cc:67] Initialize the camera or load the video.
**E20201021 17:38:35.547452 11882 demo_run_graph_main_gpu.cc:186] Failed to run the graph: ; capture.isOpened()(external/mediapipe/mediapipe/examples/desktop/demo_run_graph_main_gpu.cc:75)** 

Would you happen to have encountered this and know a solution for it? I'm running Ubuntu 18.02 and Bazel 3.4.1.

Thank you!

**Comment by Tachionstrahl** [comment]
Hi, thanks for your request.
Seems like your camera is already in use or not available. 
Please try to add the `--input_video_path` option to the run command.
Could be something like `GLOG_logtostderr=1 bazel-bin/app/prediction_gpu --calculator_graph_config_file=graphs/sign_lang_prediction_gpu.pbtxt --input_video_path=/dev/video0`, where `/dev/video0`needs to be replaced by the path to your camera.

**Comment by ishaghodgaonkar** [comment]
What would be the path to the camera on a laptop (mac)?

**Comment by Tachionstrahl** [comment]
Hi @ishaghodgaonkar,
as mentioned in our README, currently only Ubuntu 18.04 is supported.
The repository won't work on CPU out-of-the-box.

**Comment by yspollen** [comment]
Thank you so much for your help. After adding the flag --input_video_path=/dev/video0, the program ran successfully, shown in the screenshot. The camera on my mac also turned on as the green light lit up. However, I didn't seem to get a window popping up like the one in README. Is the window supposed to automatically pop up? Thank you!
![Screen Shot 2020-10-30 at 3 58 05 PM](https://user-images.githubusercontent.com/31415064/97751923-7e05f380-1ac9-11eb-9ab9-d41d6cb3c3c2.png)

**Comment by yspollen** [comment]
Nevermind! The camera showed up a few minutes later, most likely due to the program being run in a VM, but it certainly works. Thank you very much for your help!

**Comment by Tachionstrahl** [comment]
Glad to hear it!
I would appreciate your feedback on our demo.

**Comment by yspollen** [comment]
I was running your program in a Ubuntu VM so the camera wasn't exactly streaming inputs, but I believe if I weren't using a VM the program would have behaved exactly like it was demonstrated in README.
